## Numpy  - vectors and matrices

Let's start with numpy and working with vectors and matrices, at first we 
have a look on numpy arrays and try the matrix-vector-multiplication

In [1]:
import numpy as np

# have a list of values
vl=[1.23,2.23,3.23,4.23]

# and make it to a numpy array
v=np.array([vl])

print(vl,type(vl))
print(v,type(v))
print(v.ndim,v.shape)

# create a matrix
# see the value 1.0 instead of 1
# what is the difference ? 
A=np.array( [[1.0,2,3,4],[5,6,7,8]] )
print(A,type(A))
print(A.ndim,A.shape)




[1.23, 2.23, 3.23, 4.23] <class 'list'>
[[1.23 2.23 3.23 4.23]] <class 'numpy.ndarray'>
2 (1, 4)
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]] <class 'numpy.ndarray'>
2 (2, 4)


Now we look at the matrix - vector multiplication, there is a pitfall for numpy-beginners, if you have a matrix A and a vector v and write ```b=A*v``` you get **not** what you want.

In [2]:
# matrix-vector multiplication -- wrong way 
# the * is a simple array multiplication and NOT the matrix-multiplication
b=A*v
print(b,type(b),b.ndim,b.shape)

[[ 1.23  4.46  9.69 16.92]
 [ 6.15 13.38 22.61 33.84]] <class 'numpy.ndarray'> 2 (2, 4)


Next try, instead of ```b=A*v``` we do 
  * make v from a row vector to the correct column vector -- try out what happens if you skip this
  * use ```b=A.dot(u)``` or ```b=A@u``` for the matrix vector product

In [3]:
# matrix-vector multiplication again

# make v from a row vector to a column vector
# x.T gives in numpy the transposed of x
u=v.T
print(u,type(u),u.ndim,u.shape)

b=A.dot(u)
print(b,type(b),b.ndim,b.shape)

#you can also use the @ operator for matrix multiplication
c=A@u
print(c,type(c),c.ndim,c.shape)


[[1.23]
 [2.23]
 [3.23]
 [4.23]] <class 'numpy.ndarray'> 2 (4, 1)
[[32.3 ]
 [75.98]] <class 'numpy.ndarray'> 2 (2, 1)
[[32.3 ]
 [75.98]] <class 'numpy.ndarray'> 2 (2, 1)


## Task

Play around with the next code blocks to understand the element access and data types

In [4]:
# access to elements 
print(A, A.shape)
print(A[0,0])
print(A[1,2])

# try the next with 1.0 and 1 in the definition of A above 
# what happens ? 
A[1,3]=-3.14
print(A)


[[1. 2. 3. 4.]
 [5. 6. 7. 8.]] (2, 4)
1.0
7.0
[[ 1.    2.    3.    4.  ]
 [ 5.    6.    7.   -3.14]]


In [5]:
x=np.array([1,2,3,4])
print(x)
y=np.array([1.0,2.0,3.0,4.0])
print(y)

x[0]=1.5
y[0]=1.5

print(x)
print(y)



[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]
[1.5 2.  3.  4. ]


## Task

Write a function mymat(n) which takes a size argument n>0 and returns a regular nxn Matrix

In [6]:
def mymat(n):
    A=np.zeros((n,n))
    a = np.zeros((n, n), int)
    np.fill_diagonal(a,n)
    A = np.random.randint(low=1,high=5,size=(n,n))
    A = A * A.T
    A = A + a;
    return A

In [7]:
print (mymat(5))

[[ 6  8  2  8  6]
 [ 8  9  3  6  2]
 [ 2  3  9  1  8]
 [ 8  6  1 21  3]
 [ 6  2  8  3  6]]


## Task

Now use your function to create for n=3,5,10 and 15 matrices A and right hand sides $$b = A \cdot [1,1, ... 1]^T$$ and find out 
how you can use numpy.linalg.solve for solving linear systems Ax=b. Check if you get the correct solution $$[1,1,...1]^T$$

In [8]:
n=15 #adjust n accordingly
A=mymat(n)
b = np.random.randint(low=1,high=20,size=(n,1))
x = np.linalg.solve(A, b) # replace with solution of Ax=b
print(x)


[[-0.69776731]
 [ 0.83376759]
 [-0.27385707]
 [ 0.32169543]
 [ 0.48324165]
 [-0.26086329]
 [ 0.10953231]
 [ 0.72078592]
 [-0.88529451]
 [-0.83689145]
 [ 0.8496097 ]
 [ 0.89226442]
 [ 0.58964408]
 [-0.02021011]
 [-0.02565595]]


# Toeplitz and circulant matrices 

We want to create a Toeplitz matrix and also a circulant matrix, both incredibly important in signal processing. 

Toeplitz matrices are constant along the diagonals from left to rigtht, the structure is
$$T=\left[ \begin{matrix} a & b & c & d & e \\ f & a &  b &  c & d  \\ g & f & a &  b &  c \\ h& g & f & a &  b   
 \\ i & h & g & f & a  \end{matrix} \right] $$

As you can see - a Toeplitz matrix is fully defined by setting the first row and the first column.

# Task

Write a function which takes 2 vectors **c** ( the first column )  and **r** (the first row) 
as numpy arrays and returns the Toeplitz matrix, defined by this vectors. 

In [9]:
def toeplitz(c,r):
    if(r[0] != c[0] ):
        raise ValueError('Error c[0] must be equal r[0] but  %f %f ' % (c[0],r[0]))
    n = r.size
    T = np.zeros((n,n))
    T[:,0] = c;
    col = c;
    for i in range(1,n):
        col = np.insert(col, 0, r[i])
        col = col[:-1]
        T[:,i] = col
    # TODO
    
    return T

In [10]:

r=np.array([1,2,3,4])
c=np.array([1,5,6,7])
T=toeplitz(c,r)
print(T)


[[1. 2. 3. 4.]
 [5. 1. 2. 3.]
 [6. 5. 1. 2.]
 [7. 6. 5. 1.]]



## Circulant matrices 

Circulant matrices are square matrices and fully defined by its first column **c** and have the structure

$$C=\left[ \begin{matrix} 
a & e & d & c & b \\ 
b & a & e & d & c  \\ 
c & b & a & e & d \\ 
d & c & b & a & e    \\ 
e & d & c & b & a  \end{matrix} \right] $$

You can see that Circulant matrices are a special kind of Toeplitz matrices.

## Task

Write a function which takes a vector **c** as 1 numpy array 
and returns the Circulant matrix, defined by this vector. 


In [11]:
def circulant(c):
    n = c.size
    C = np.zeros((n,n))
    C[:,0] = c;
    col = c;
    for i in range(1,n):
        col = np.insert(col, 0, col[n-1])
        col = col[:-1]
        C[:,i] = col
    return C
    

In [12]:

C=circulant(r)

In [13]:
print(C)


[[1. 4. 3. 2.]
 [2. 1. 4. 3.]
 [3. 2. 1. 4.]
 [4. 3. 2. 1.]]


# Fourier matrix

The Fourier matrix $F$ of size $n \times n$ is defined as
$$
F=\frac{1}{\sqrt{n}}
\left[
\begin{array}
\cdot & \cdot & \cdot \\
\cdot & \omega^{jk} & \cdot \\
\cdot & \cdot & \cdot \\
\end{array}
\right]_{j,k=0}^{n-1}
$$
where $\omega$ is the n-th primitive root of unity, i.e. $$\omega=e^{-2\Pi i / n}$$

## Task

Write a function which computes for given size **n** the Fourier matrix $F$.

(Later we will use scipy - there is the Fouriermatrix given as build in, but now we do it by hand)
  * Hint 1 : The complex number **i** you can get in numpy as **1.j**
  * Hint 2 : $\Pi$ you get as np.pi
  * Hint 3 : in complex computations initialize your data types correct, f.e. 
    ``` F=np.zeros((n,n),dtype=complex) ``` . Try out what happens if you do it as 
    ``` F=np.zeros((n,n)) ```


In [14]:
def fourier(n):
    # create a complex zero matrix
    F=np.zeros((n,n),dtype=complex)
    # TODO

    return F

In [15]:
F=fourier(4)
print(F)

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]


## Diagonalization of a circulant matrix

With the help of our Fouriermatrix $F$  we can diagonlize the circulant matrix $C$ with
$$ D = \bar{F}C F $$
where $\bar{F}$ is the complex conjugate matrix of $F$, let's try this out.

In [16]:
# matrix multiplication with the @ operator
D=np.conjugate(F)@C@F
print(D)


[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]


The result $D$ is not very good readable because of the zeros written as small numbers in range $10^{-16}$. So we do some matrix cosmetic and cut off small numbers

In [17]:
tol=1e-12
D.real[abs(D.real) < tol] = 0.0
D.imag[abs(D.imag) < tol] = 0.0

print(D.real)
#print(D.imag)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]



Now $D$ looks like a diagonal matrix :-) 

The construction of $F$ and $C$ can be avoided if the **Fast Fourier Transfor (FFT)** is used and the complexity reduces to something that is $\mathcal{O}(n\mathrm{log}(n))$ rather than $\mathcal{O}(n^2)$

[here](https://math.mit.edu/icg/resources/teaching/18.085-spring2015/toeplitz.pdf) you can find the information of how to embedd a Toeplitz matrix into a circulant matrix. Implement this function and verify with a DFT of the double size that this is diagonalized using $F$.



